# Generated by Django 5.1.7 on 2025-04-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wingmanusers',
            name='orientation',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
