# Generated by Django 5.1.7 on 2025-03-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_llamaresponse_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='WingmanUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('email', models.TextField(unique=True)),
                ('sex', models.TextField(max_length=10)),
                ('age', models.IntegerField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
