# Generated by Django 5.1.7 on 2025-03-25 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_wingmanusers_password_alter_wingmanusers_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='llamaresponse',
            name='context',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='LlamaChatting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.wingmanusers')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
